
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int EmClose = 60;
  public static final int AcronymOpen = 7;
  public static final int FontClose = 64;
  public static final int DdOpen = 45;
  public static final int HrOpen = 75;
  public static final int PClose = 124;
  public static final int DirOpen = 51;
  public static final int BOpen = 15;
  public static final int TbodyClose = 158;
  public static final int SampClose = 136;
  public static final int ImgOpen = 83;
  public static final int NOHREF_ATTR = 197;
  public static final int IOpen = 79;
  public static final int NoscriptClose = 114;
  public static final int TdOpen = 159;
  public static final int UlOpen = 177;
  public static final int NOSHADE_ATTR = 186;
  public static final int TfootOpen = 163;
  public static final int CaptionOpen = 33;
  public static final int POpen = 123;
  public static final int OptionOpen = 121;
  public static final int MetaOpen = 107;
  public static final int BlockquoteOpen = 25;
  public static final int OptgroupOpen = 119;
  public static final int AbbrOpen = 5;
  public static final int SpanOpen = 143;
  public static final int HEIGHT_ATTR = 212;
  public static final int METHOD_ATTR = 210;
  public static final int IframeClose = 82;
  public static final int TrOpen = 171;
  public static final int HtmlClose = 78;
  public static final int CELLSPACING_ATTR = 229;
  public static final int AppletClose = 12;
  public static final int SelectClose = 140;
  public static final int HnClose = 74;
  public static final int FrameOpen = 67;
  public static final int HREF_ATTR = 188;
  public static final int ButtonOpen = 31;
  public static final int ParamClose = 126;
  public static final int HnOpen = 73;
  public static final int USEMAP_ATTR = 216;
  public static final int NoframesClose = 112;
  public static final int Identifier = 238;
  public static final int COLOR_ATTR = 205;
  public static final int HrClose = 76;
  public static final int ISMAP_ATTR = 217;
  public static final int FormClose = 66;
  public static final int AppletOpen = 11;
  public static final int BigOpen = 23;
  public static final int XmpOpen = 181;
  public static final int ListingOpen = 101;
  public static final int REL_ATTR = 189;
  public static final int HSPACE_ATTR = 213;
  public static final int BORDER_ATTR = 215;
  public static final int ScriptOpen = 137;
  public static final int IClose = 80;
  public static final int ColgroupClose = 44;
  public static final int StyleOpen = 149;
  public static final int ALIGN_ATTR = 183;
  public static final int CiteClose = 38;
  public static final int AClose = 4;
  public static final int SOpen = 133;
  public static final int MapClose = 104;
  public static final int BodyClose = 28;
  public static final int ColOpen = 41;
  public static final int ATTRIBUTE_DATA = 239;
  public static final int TdClose = 160;
  public static final int MetaClose = 108;
  public static final int AreaOpen = 13;
  public static final int IsindexClose = 90;
  public static final int QClose = 132;
  public static final int ALINK_ATTR = 203;
  public static final int TableOpen = 155;
  public static final int AbbrClose = 6;
  public static final int MapOpen = 103;
  public static final int EOF = 0;
  public static final int FrameClose = 68;
  public static final int ThClose = 166;
  public static final int AOpen = 3;
  public static final int VSPACE_ATTR = 214;
  public static final int UClose = 176;
  public static final int SubOpen = 151;
  public static final int LinkOpen = 99;
  public static final int SpanClose = 144;
  public static final int TEXT_ATTR = 200;
  public static final int BrClose = 30;
  public static final int XmpClose = 182;
  public static final int HtmlOpen = 77;
  public static final int UlClose = 178;
  public static final int AddressOpen = 9;
  public static final int TitleOpen = 169;
  public static final int SupOpen = 153;
  public static final int VLINK_ATTR = 202;
  public static final int DfnOpen = 49;
  public static final int ID_ATTR = 223;
  public static final int URN_ATTR = 192;
  public static final int CLEAR_ATTR = 207;
  public static final int TtClose = 174;
  public static final int ROWS_ATTR = 235;
  public static final int CELLPADDING_ATTR = 230;
  public static final int CodeClose = 40;
  public static final int VERSION_ATTR = 204;
  public static final int TableClose = 156;
  public static final int AddressClose = 10;
  public static final int FramesetClose = 70;
  public static final int CONTENT = 237;
  public static final int TitleClose = 170;
  public static final int DelClose = 48;
  public static final int BaseOpen = 17;
  public static final int InputOpen = 85;
  public static final int PlaintextOpen = 127;
  public static final int OlClose = 118;
  public static final int BigClose = 24;
  public static final int FramesetOpen = 69;
  public static final int ColgroupOpen = 43;
  public static final int InputClose = 86;
  public static final int SIZE_ATTR_HR = 184;
  public static final int BasefontOpen = 19;
  public static final int CenterClose = 36;
  public static final int MAXLENGTH_ATTR = 220;
  public static final int VarClose = 180;
  public static final int TextareaClose = 162;
  public static final int START_ATTR = 226;
  public static final int BClose = 16;
  public static final int ImgClose = 84;
  public static final int StyleClose = 150;
  public static final int DtOpen = 57;
  public static final int BaseClose = 18;
  public static final int OlOpen = 117;
  public static final int BACKGROUND_ATTR = 199;
  public static final int InsClose = 88;
  public static final int FieldsetOpen = 61;
  public static final int MenuClose = 106;
  public static final int LegendClose = 96;
  public static final int CenterOpen = 35;
  public static final int BrOpen = 29;
  public static final int TtOpen = 173;
  public static final int COLSPAN_ATTR = 233;
  public static final int KbdClose = 92;
  public static final int NAME_ATTR = 187;
  public static final int LabelClose = 94;
  public static final int ListingClose = 102;
  public static final int VarOpen = 179;
  public static final int LiOpen = 97;
  public static final int BlockquoteClose = 26;
  public static final int NOWRAP_ATTR = 234;
  public static final int TheadClose = 168;
  public static final int CodeOpen = 39;
  public static final int ROWSPAN_ATTR = 232;
  public static final int COMPACT_ATTR = 206;
  public static final int TbodyOpen = 157;
  public static final int SupClose = 154;
  public static final int ParamOpen = 125;
  public static final int PROMPT_ATTR = 222;
  public static final int BdoClose = 22;
  public static final int PlaintextClose = 128;
  public static final int SmallOpen = 141;
  public static final int BdoOpen = 21;
  public static final int NextidOpen = 109;
  public static final int TYPE_ATTR = 218;
  public static final int AreaClose = 14;
  public static final int StrikeOpen = 145;
  public static final int DdClose = 46;
  public static final int UOpen = 175;
  public static final int BodyOpen = 27;
  public static final int DelOpen = 47;
  public static final int ENCTYPE_ATTR = 209;
  public static final int ButtonClose = 32;
  public static final int StrikeClose = 146;
  public static final int DlClose = 56;
  public static final int EmOpen = 59;
  public static final int PreOpen = 129;
  public static final int FieldsetClose = 62;
  public static final int TextareaOpen = 161;
  public static final int SmallClose = 142;
  public static final int DlOpen = 55;
  public static final int SHAPE_ATTR = 194;
  public static final int SelectOpen = 139;
  public static final int COORDS_ATTR = 195;
  public static final int StrongOpen = 147;
  public static final int ScriptClose = 138;
  public static final int COLS_ATTR = 236;
  public static final int REV_ATTR = 190;
  public static final int NoframesOpen = 111;
  public static final int MULTIPLE_ATTR = 228;
  public static final int SClose = 134;
  public static final int QOpen = 131;
  public static final int FontOpen = 63;
  public static final int DtClose = 58;
  public static final int LiClose = 98;
  public static final int BGCOLOR_ATTR = 198;
  public static final int FormOpen = 65;
  public static final int ObjectClose = 116;
  public static final int ObjectOpen = 115;
  public static final int TfootClose = 164;
  public static final int HeadOpen = 71;
  public static final int CiteOpen = 37;
  public static final int LINK_ATTR = 201;
  public static final int IframeOpen = 81;
  public static final int TheadOpen = 167;
  public static final int LinkClose = 100;
  public static final int AcronymClose = 8;
  public static final int HTTP_EQUIV_ATTR = 224;
  public static final int OptgroupClose = 120;
  public static final int DirClose = 52;
  public static final int CaptionClose = 34;
  public static final int NextidClose = 110;
  public static final int ACTION_ATTR = 208;
  public static final int VALIGN_ATTR = 231;
  public static final int METHODS_ATTR = 193;
  public static final int HeadClose = 72;
  public static final int OptionClose = 122;
  public static final int TrClose = 172;
  public static final int IsindexOpen = 89;
  public static final int CHECKED_ATTR = 221;
  public static final int SRC_ATTR = 211;
  public static final int DivOpen = 53;
  public static final int DivClose = 54;
  public static final int MenuOpen = 105;
  public static final int error = 1;
  public static final int NoscriptOpen = 113;
  public static final int InsOpen = 87;
  public static final int SELECTED_ATTR = 227;
  public static final int WIDTH_ATTR_HR = 185;
  public static final int ColClose = 42;
  public static final int ThOpen = 165;
  public static final int VALUE_ATTR = 219;
  public static final int PreClose = 130;
  public static final int LabelOpen = 93;
  public static final int ERROR = 2;
  public static final int DfnClose = 50;
  public static final int SampOpen = 135;
  public static final int BasefontClose = 20;
  public static final int LegendOpen = 95;
  public static final int SubClose = 152;
  public static final int CONTENT_ATTR = 225;
  public static final int TITLE_ATTR = 191;
  public static final int KbdOpen = 91;
  public static final int StrongClose = 148;
  public static final int ALT_ATTR = 196;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ERROR",
  "AOpen",
  "AClose",
  "AbbrOpen",
  "AbbrClose",
  "AcronymOpen",
  "AcronymClose",
  "AddressOpen",
  "AddressClose",
  "AppletOpen",
  "AppletClose",
  "AreaOpen",
  "AreaClose",
  "BOpen",
  "BClose",
  "BaseOpen",
  "BaseClose",
  "BasefontOpen",
  "BasefontClose",
  "BdoOpen",
  "BdoClose",
  "BigOpen",
  "BigClose",
  "BlockquoteOpen",
  "BlockquoteClose",
  "BodyOpen",
  "BodyClose",
  "BrOpen",
  "BrClose",
  "ButtonOpen",
  "ButtonClose",
  "CaptionOpen",
  "CaptionClose",
  "CenterOpen",
  "CenterClose",
  "CiteOpen",
  "CiteClose",
  "CodeOpen",
  "CodeClose",
  "ColOpen",
  "ColClose",
  "ColgroupOpen",
  "ColgroupClose",
  "DdOpen",
  "DdClose",
  "DelOpen",
  "DelClose",
  "DfnOpen",
  "DfnClose",
  "DirOpen",
  "DirClose",
  "DivOpen",
  "DivClose",
  "DlOpen",
  "DlClose",
  "DtOpen",
  "DtClose",
  "EmOpen",
  "EmClose",
  "FieldsetOpen",
  "FieldsetClose",
  "FontOpen",
  "FontClose",
  "FormOpen",
  "FormClose",
  "FrameOpen",
  "FrameClose",
  "FramesetOpen",
  "FramesetClose",
  "HeadOpen",
  "HeadClose",
  "HnOpen",
  "HnClose",
  "HrOpen",
  "HrClose",
  "HtmlOpen",
  "HtmlClose",
  "IOpen",
  "IClose",
  "IframeOpen",
  "IframeClose",
  "ImgOpen",
  "ImgClose",
  "InputOpen",
  "InputClose",
  "InsOpen",
  "InsClose",
  "IsindexOpen",
  "IsindexClose",
  "KbdOpen",
  "KbdClose",
  "LabelOpen",
  "LabelClose",
  "LegendOpen",
  "LegendClose",
  "LiOpen",
  "LiClose",
  "LinkOpen",
  "LinkClose",
  "ListingOpen",
  "ListingClose",
  "MapOpen",
  "MapClose",
  "MenuOpen",
  "MenuClose",
  "MetaOpen",
  "MetaClose",
  "NextidOpen",
  "NextidClose",
  "NoframesOpen",
  "NoframesClose",
  "NoscriptOpen",
  "NoscriptClose",
  "ObjectOpen",
  "ObjectClose",
  "OlOpen",
  "OlClose",
  "OptgroupOpen",
  "OptgroupClose",
  "OptionOpen",
  "OptionClose",
  "POpen",
  "PClose",
  "ParamOpen",
  "ParamClose",
  "PlaintextOpen",
  "PlaintextClose",
  "PreOpen",
  "PreClose",
  "QOpen",
  "QClose",
  "SOpen",
  "SClose",
  "SampOpen",
  "SampClose",
  "ScriptOpen",
  "ScriptClose",
  "SelectOpen",
  "SelectClose",
  "SmallOpen",
  "SmallClose",
  "SpanOpen",
  "SpanClose",
  "StrikeOpen",
  "StrikeClose",
  "StrongOpen",
  "StrongClose",
  "StyleOpen",
  "StyleClose",
  "SubOpen",
  "SubClose",
  "SupOpen",
  "SupClose",
  "TableOpen",
  "TableClose",
  "TbodyOpen",
  "TbodyClose",
  "TdOpen",
  "TdClose",
  "TextareaOpen",
  "TextareaClose",
  "TfootOpen",
  "TfootClose",
  "ThOpen",
  "ThClose",
  "TheadOpen",
  "TheadClose",
  "TitleOpen",
  "TitleClose",
  "TrOpen",
  "TrClose",
  "TtOpen",
  "TtClose",
  "UOpen",
  "UClose",
  "UlOpen",
  "UlClose",
  "VarOpen",
  "VarClose",
  "XmpOpen",
  "XmpClose",
  "ALIGN_ATTR",
  "SIZE_ATTR_HR",
  "WIDTH_ATTR_HR",
  "NOSHADE_ATTR",
  "NAME_ATTR",
  "HREF_ATTR",
  "REL_ATTR",
  "REV_ATTR",
  "TITLE_ATTR",
  "URN_ATTR",
  "METHODS_ATTR",
  "SHAPE_ATTR",
  "COORDS_ATTR",
  "ALT_ATTR",
  "NOHREF_ATTR",
  "BGCOLOR_ATTR",
  "BACKGROUND_ATTR",
  "TEXT_ATTR",
  "LINK_ATTR",
  "VLINK_ATTR",
  "ALINK_ATTR",
  "VERSION_ATTR",
  "COLOR_ATTR",
  "COMPACT_ATTR",
  "CLEAR_ATTR",
  "ACTION_ATTR",
  "ENCTYPE_ATTR",
  "METHOD_ATTR",
  "SRC_ATTR",
  "HEIGHT_ATTR",
  "HSPACE_ATTR",
  "VSPACE_ATTR",
  "BORDER_ATTR",
  "USEMAP_ATTR",
  "ISMAP_ATTR",
  "TYPE_ATTR",
  "VALUE_ATTR",
  "MAXLENGTH_ATTR",
  "CHECKED_ATTR",
  "PROMPT_ATTR",
  "ID_ATTR",
  "HTTP_EQUIV_ATTR",
  "CONTENT_ATTR",
  "START_ATTR",
  "SELECTED_ATTR",
  "MULTIPLE_ATTR",
  "CELLSPACING_ATTR",
  "CELLPADDING_ATTR",
  "VALIGN_ATTR",
  "ROWSPAN_ATTR",
  "COLSPAN_ATTR",
  "NOWRAP_ATTR",
  "ROWS_ATTR",
  "COLS_ATTR",
  "CONTENT",
  "Identifier",
  "ATTRIBUTE_DATA"
  };
}

